name: SystemF
version: 0.1.0.0
github: "zehaochen19/SystemF"
license: MIT
author: "Zehao Chen"
maintainer: "zehaochen19@gmail.com"
copyright: "2019 Zehao Chen"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/zehaochen19/SystemF#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - extra
  - polysemy
  - megaparsec
  - parser-combinators
  - text

library:
  source-dirs: src

executables:
  systemf:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SystemF

tests:
  SystemF-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SystemF
      - hspec
